---
title: "complaint"
output: html_document
date: "2022-11-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
```

```{r}
cp <- read_csv("../00_data/cp_oz.csv")
head(cp)
```
```{r}
summary(cp)
```
```{r}
##designated percentage
cp_de <- cp %>%
  count(DESIGNATED)
cp_de %>%
  mutate(Percentage=paste0(round(n/sum(n)*100,2),"%"))
##designated and low income community
cp_dl <- cp %>%
  count(LIC, DESIGNATED, sort=TRUE)
cp_dl %>%
  mutate(Percentage=paste0(round(n/sum(n)*100,2),"%"))
```

```{r}

##law type percentage
cp_lawlevel <- cp %>%
  count(law_cat_cd, crm_atpt_cptd_cd, sort=TRUE)
cp_lawlevel %>%
  mutate(Percentage=paste0(round(n/sum(n)*100,2),"%"))
cp_lawlevel1 <- cp %>%
  filter(DESIGNATED==TRUE) %>%
  count(law_cat_cd, crm_atpt_cptd_cd, sort=TRUE)
cp_lawlevel1 %>%
  mutate(Percentage=paste0(round(n/sum(n)*100,2),"%"))
```

```{r}
#offence type percentage
cp_offence <- cp %>%
  count(ofns_desc, sort=TRUE)
cp_offence %>%
  mutate(Percentage=paste0(round(n/sum(n)*100,2),"%"))
cp_offence1 <- cp %>%
  filter(DESIGNATED==TRUE)%>%
  count(ofns_desc, sort=TRUE)
cp_offence1 %>%
  mutate(Percentage=paste0(round(n/sum(n)*100,2),"%"))
```

```{r}
##boro percentage
cp_boro <- cp %>%
  count(boro_nm,sort=TRUE)
cp_boro %>%
  mutate(Percentage=paste0(round(n/sum(n)*100,2),"%"))
cp_boro1 <- cp %>%
  filter(DESIGNATED==TRUE)%>%
  count(boro_nm,sort=TRUE)
cp_boro1 %>%
  mutate(Percentage=paste0(round(n/sum(n)*100,2),"%"))

```
```{r}
## suspect 
cp_sus <- cp %>%
  count(susp_race, susp_sex, sort=TRUE)
cp_sus %>%
  mutate(Percentage=paste0(round(n/sum(n)*100,2),"%"))
cp_sus1 <- cp %>%
  filter(DESIGNATED==TRUE)%>%
  count(susp_race, susp_sex, sort=TRUE)
cp_sus1 %>%
  mutate(Percentage=paste0(round(n/sum(n)*100,2),"%"))
```
```{r}
##victim
cp_vic <- cp %>%
  count(vic_race, vic_sex, sort=TRUE)
cp_vic %>%
  mutate(Percentage=paste0(round(n/sum(n)*100,2),"%"))
cp_vic1 <- cp %>%
  filter(DESIGNATED==TRUE)%>%
  count(vic_race, vic_sex, sort=TRUE)
cp_vic1 %>%
  mutate(Percentage=paste0(round(n/sum(n)*100,2),"%"))
```

```{r}
##time trend of complaints in different boro
  ggplot(cp %>% filter((DESIGNATED == TRUE) )) +
  geom_histogram(mapping = aes(x = cmplnt_fr_dt, fill = boro_nm), alpha = 0.5) +
  labs(title = "NYC complaints Over Time (boro)",x="date of occurance for the report event", y = "count")
```
```{r}
##time trend of complaints of each level of offence
ggplot(cp %>% filter((DESIGNATED == TRUE) )) +
  geom_histogram(mapping = aes(x = cmplnt_fr_dt, fill = law_cat_cd), alpha = 0.5, position = "identity") +
  labs(title = "NYC complaints Over Time (level of offence)",x="date of occurance for the report event", y = "count")
```

```{r}

```

